version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - DEBUG=1
      - SERVICES=sns,sqs
      - DEFAULT_REGION=us-east-1
      - HOSTNAME_EXTERNAL=localstack
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    ports:
      - "4566:4566"
    volumes:
      - "./localstack-init:/docker-entrypoint-initaws.d"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/health"]
      interval: 5s
      timeout: 10s
      retries: 3

volumes:
  localstack-data:
