name: Build and Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['8.0.x']

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    
    - name: Restore dependencies
      run: dotnet restore SNS.EventChannel/EventChannel.csproj
      
    - name: Build
      run: dotnet build SNS.EventChannel/EventChannel.csproj --no-restore --configuration Release
    
    - name: Test
      run: dotnet test SNS.EventChannel.Tests/**.csproj --no-build --verbosity normal --configuration Release
      
  # New job that only runs on release
  release:
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Extract version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
    
    - name: Restore dependencies
      run: dotnet restore SNS.EventChannel/EventChannel.csproj
      
    - name: Build
      run: dotnet build SNS.EventChannel/EventChannel.csproj --configuration Release --no-restore /p:Version=${{ steps.get_version.outputs.VERSION }}
    
    - name: Pack
      run: dotnet pack --no-build --configuration Release SNS.EventChannel/EventChannel.csproj -o ./artifacts /p:Version=${{ steps.get_version.outputs.VERSION }}
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nuget-packages
        path: ./artifacts/*.nupkg
        
    - name: Setup NuGet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        source-url: https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}
        
    - name: Publish to NuGet
      run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
